---
ProfileName: DragenGermline_IDTLMN_TAG_WGS
Version: 1.0
LibraryPrepKitName: IlluminaDNAPCRFree
IndexAdapterKitName: IDTIlmnDNARNAUDISetADTagmentation_DNAPCRFree
IndexAdapterKitNameReadable: "IDT-Ilmn DNA-RNA UD Indexes Set ABCD Tagmentation"

PipelineData:
  ProfileName: DragenGermline_IDTLMN_TAG_WGS
  Pipeline: DragenGermline
  ReferenceGenomeDir: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2
  VariantCallingMode: AllVariantCallers

