---
# application_settings.yaml

BCLConvert:
    BCLConvert_Settings:
        SoftwareVersion
        AppVersion
        FastqCompressionFormat
        AdapterRead1
        AdapterRead2
        BarcodeMismatchesIndex1
        BarcodeMismatchesIndex2
        OverrideCycles

    BCLConvert_Data:
        SampleID
        Lane
        Index
        Index2

DragenEnrichment:
    DragenEnrichment_Settings:
        SoftwareVersion
        AppVersion
        KeepFastQ
        MapAlignOutFormat
        ReferenceGenomeDir
        Bedfile
        GermlineOrSomatic
        AuxNoiseBaselineFile
        AuxCnvPanelOfNormalsFile
        VariantCallingMode
    DragenEnrichment_Data:
        SampleID

DragenGermline:
    DragenGermline_Settings:
        SoftwareVersion
        AppVersion
        KeepFastQ
        MapAlignOutFormat
        ReferenceGenomeDir
        VariantCallingMode

    DragenGermline_Data:
        SampleID

DragenRna:
    DragenRna_Settings:
        SoftwareVersion
        AppVersion
        KeepFastQ
        MapAlignOutFormat
        ReferenceGenomeDir
        DifferentialExpressionEnable
        RnaGeneAnnotationFile
        RnaPipelineMode
        DownSampleNumReads

    DragenRna_Data:
        SampleID
        Comparison1
        Comparison2
        Comparison3
        Comparison4
        Comparison5













