---
# application_settings.yaml

application_name: BCLConvert
settings_name: BCLConvert_Settings
settings:
  SoftwareVersion:
    - 4.1.7
    - 4.1.5
  AppVersion:
    - 4.1.7
  FastqCompressionFormat:
    - dragen
    - gzip
  AdapterRead1: CTGTCTCTTATACACATCT+ATGTGTATAAGAGACA
  AdapterRead2: CTGTCTCTTATACACATCT+ATGTGTATAAGAGACA
  BarcodeMismatchesIndex1:
    - 0
    - 1
    - 2
  BarcodeMismatchesIndex2:
    - 0
    - 1
    - 2
  OverrideCycles:
    Read 1: Y151
    Read 2: Y151
    Index 1: I10
    Index 2: I10

data_name: BCLConvert_Data
data:
  - SampleID
  - Lane
  - Index
  - Index2