---
# application_settings.yaml

application_name: DragenGermline
settings_name: DragenGermline_Settings
settings:
  SoftwareVersion:
    - 4.1.7
  KeepFastQ:
    - true
    - false
  MapAlignOutFormat:
    - cram
    - bam
    - none
  ReferenceGenomeDir:
    - Readable: "Homo sapiens [UCSC] hg19 Alt Masked v2 Graph"
      ID: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2
    - Readable: "Homo sapiens [1000 Genomes] hg38 Alt Masked v2 Graph"
      ID: hg19-alt_masked.cnv.graph.hla.rna-8-1667495412-2
  VariantCallingMode:
    - AllVariantCallers
    - SmallVariantCaller
    - None
  LibraryPrepKit:
    LibraryPrepKitName: IlluminaDNAPCRFree
    IndexAdapterKitNames:
      - IndexAdapterKitName: IDTIlmnDNARNAUDISetADTagmentation_DNAPCRFree
        IndexAdapterKitNameReadable: "IDT-Ilmn DNA-RNA UD Indexes Set A Tagmentation"
      - IndexAdapterKitName: IDTIlmnDNARNAUDISetBTagmentation_DNAPCRFree
        IndexAdapterKitNameReadable: "IDT-Ilmn DNA-RNA UD Indexes Set B Tagmentation"
      - IndexAdapterKitName: IDTIlmnDNARNAUDISetCTagmentation_DNAPCRFree
        IndexAdapterKitNameReadable: "IDT-Ilmn DNA-RNA UD Indexes Set C Tagmentation"
      - IndexAdapterKitName: IDTIlmnDNARNAUDISetDTagmentation_DNAPCRFree
        IndexAdapterKitNameReadable: "IDT-Ilmn DNA-RNA UD Indexes Set D Tagmentation"


data_name: DragenGermline_Data
data:
  - SampleID
