---
LibraryPrepKitName: ILMNStrandedmRNA
IndexAdapterKitName: IDTIlmnRNAUDISetABCDLigation
IndexAdapterKitNameReadable: "IDT-Ilmn RNA UD Indexes Set ABCD Ligation"

Profile:
  BCLConvert:
    BCLConvert_Settings:
      SoftwareVersion: '4.1.7'
      FastqCompressionFormat: gzip

    BCLConvert_Data:
      AdapterRead1: CTGTCTCTTATACACATCT
      AdapterRead2: CTGTCTCTTATACACATCT
      OverrideCycles:
        Read 1: 76
        Read 2: 76
        Index 1: 10
        Index 2: 10
      BarcodeMismatchesIndex1: 1
      BarcodeMismatchesIndex2: 1

  DragenRna_Settings:
    SoftwareVersion: '4.1.7'
    MapAlignOutFormat: bam
    KeepFastq: true
    RnaPipelineMode: FullPipeline
    DifferentialExpressionEnable: false

  DragenRna_Data:
    ReferenceGenomeDir: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2


