---
MethodType: WGS
Method: WGS
Description: Whole Genome Sequencing
Version: 1.0

ApplicationProfiles:
  - ApplicationProfile: BCLConvertNextera
    ApplicationProfileVersion: 1.0

  - ApplicationProfile: DragenGermlineIdtWgs
    ApplicationProfileVersion: 1.0

