---
Version: 1.0
ApplicationProfileName: BCLConvert
Application: BCLConvert

Settings:
  SoftwareVersion: 4.1.23
  FastqCompressionFormat: gzip

Data:
  BarcodeMismatchesIndex1: 1
  BarcodeMismatchesIndex2: 1
  AdapterRead1: CTGTCTCTTATACACATCTCCGAGCCCACGAGAC+ATGTGTATAAGAGACA
  AdapterRead2: CTGTCTCTTATACACATCTCGCAGGGGATAGTCAGATGACGCTGCCGACGA+ATGTGTATAAGAGACA

DataFields:
  - Sample_ID
  - Lane
  - Index
  - Index2
  - OverrideCycles
  - AdapterRead1
  - AdapterRead2
  - BarcodeMismatchesIndex1
  - BarcodeMismatchesIndex2



