---
Version: 1.0
ApplicationGroupName: Dragen
ApplicationProfileName: DragenEnrichment_IDT_Germline
Application: DragenEnrichment

Settings:
  SoftwareVersion: 4.1.23
  MapAlignOutFormat: bam
  KeepFastq: true

Data:
  BedFile: na
  ReferenceGenomeDir: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2
  VariantCallingMode: AllVariantCallers
  GermlineOrSomatic: germline
  AuxNoiseBaselineFile: na
  AuxCnvPanelOfNormalsFile: na

DataFields:
  - Sample_ID
  - ReferenceGenomeDir
  - BedFile
  - GermlineOrSomatic
  - AuxNoiseBaselineFile
  - AuxCnvPanelOfNormalsFile
  - VariantCallingMode

