---
OnBoardDragen: true
ApplicationProfileVersion: 1.0
ApplicationProfileName: DragenEnrichment_IDT_Germline
Application: DragenEnrichment

ApplicationSettings:
  SoftwareVersion: 4.1.23
  MapAlignOutFormat: bam
  KeepFastq: true

ApplicationData:
  BedFile: na
  ReferenceGenomeDir: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2
  VariantCallingMode: AllVariantCallers
  GermlineOrSomatic: germline
  AuxNoiseBaselineFile: na
  AuxCnvPanelOfNormalsFile: na

ApplicationDataFields:
  - ReferenceGenomeDir
  - BedFile
  - GermlineOrSomatic
  - AuxNoiseBaselineFile
  - AuxCnvPanelOfNormalsFile
  - VariantCallingMode
  - Sample_ID

