---
ApplicationProfileVersion: 1.0
ApplicationProfile: DragenSomatic_IDT
Application: DragenSomatic

ApplicationSettings:
  SoftwareVersion: 4.1.23
  MapAlignOutFormat: bam
  KeepFastq: true

ApplicationData:
  ReferenceGenomeDir: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2
  VariantCallingMode: AllVariantCallers
  AuxCnvPanelOfNormalsFile: na
#  AuxNoiseBaselineFile: na
#  AuxSvNoiseBaselineFile: na
#  AuxCnvPopBAlleleVcfFile: na
#  AuxGermlineTaggingFile: na
#  AuxCnvPanelOfNormalsFile: na

ApplicationDataFields:
  - ReferenceGenomeDir
  - VariantCallingMode
  - AuxNoiseBaselineFile
  - AuxSvNoiseBaselineFile
  - AuxCnvPopBAlleleVcfFile
  - AuxGermlineTaggingFile
  - AuxCnvPanelOfNormalsFile
  - Sample_ID
