---
Version: 1.0
OnBoard: true
ApplicationGroupName: Dragen
ApplicationName: BCLConvert_2
Application: BCLConvert

Settings:
  SoftwareVersion: 4.1.22
  FastqCompressionFormat: gzip

Data:
  BarcodeMismatchesIndex1: 1
  BarcodeMismatchesIndex2: 1
  AdapterRead1: CTGTCTCTTATACACATCT+AGATGTGTATAAGAGACAG
  AdapterRead2: CTGTCTCTTATACACATCT+AGATGTGTATAAGAGACAG

DataFields:
  - Sample_ID
  - Lane
  - IndexI7
  - IndexI5
  - OverrideCycles
  - BarcodeMismatchesIndex1
  - BarcodeMismatchesIndex2
  - AdapterRead1
  - AdapterRead2

Translate:
  IndexI7: Index
  IndexI5: Index2



