---
Version: 1.0
ApplicationGroupName: Dragen
ApplicationName: BCLConvert_Nextera
Application: BCLConvert

Settings:
  SoftwareVersion: 4.1.23
  FastqCompressionFormat: gzip
  AdapterRead1: CTGTCTCTTATACACATCT+AGATGTGTATAAGAGACAG
  AdapterRead2: CTGTCTCTTATACACATCT+AGATGTGTATAAGAGACAG

Data:
  BarcodeMismatchesIndex1: 1
  BarcodeMismatchesIndex2: 1

DataFields:
  - Sample_ID
  - Lane
  - IndexI7
  - IndexI5
  - OverrideCycles
  - BarcodeMismatchesIndex1
  - BarcodeMismatchesIndex2

Translate:
  IndexI7: Index
  IndexI5: Index2



