---
Version: 1.0
OnBoard: true
ApplicationGroupName: Dragen
ApplicationName: DragenEnrichment_SomaticIDTGms560
Application: DragenEnrichment

Settings:
  SoftwareVersion: 4.1.23
  AppVersion: 1.2.1
  MapAlignOutFormat: bam
  KeepFastq: true

Data:
  BedFile: gms560_hg38.BedFile
  ReferenceGenomeDir: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2
  VariantCallingMode: AllVariantCallers
  GermlineOrSomatic: somatic
  AuxNoiseBaselineFile: na
  AuxCnvPanelOfNormalsFile: na

DataFields:
  - ReferenceGenomeDir
  - BedFile
  - GermlineOrSomatic
  - AuxNoiseBaselineFile
  - AuxCnvPanelOfNormalsFile
  - VariantCallingMode
  - Sample_ID