---
ApplicationProfileVersion: 1.0
ApplicationProfile: DragenGermline_IDTLMN_TAG_WGS
Application: DragenGermline

ApplicationSettings:
  SoftwareVersion: 4.1.23
  KeepFastQ: True
  MapAlignOutFormat: bam

ApplicationData:
  ReferenceGenomeDir: hg38-alt_masked.cnv.graph.hla.rna-8-1667497097-2
  VariantCallingMode: AllVariantCallers
  QcCoverage1BedFile: na
  QcCoverage2BedFile: na
  QcCoverage3BedFile: na
  QcCrossContaminationVcfFile: na

ApplicationDataFields:
  - ReferenceGenomeDir
  - VariantCallingMode
  - QcCoverage1BedFile
  - QcCoverage2BedFile
  - QcCoverage3BedFile
  - QcCrossContaminationVcfFile
  - Sample_ID
