---
Samples:
  - Lane
  - Sample_ID
Indexes:
  - FixedPos
  - Name_I7
  - Index_I7
  - Name_I5
  - Index_I5
  - IndexDefinitionKitName
BCLConvert:
  - UsedCycles
  - BarcodeMismatchesIndex1
  - BarcodeMismatchesIndex2
  - AdapterRead1
  - AdapterRead2
  - FastqCompressionFormat
Profile:
  - ProfileName
  - Pipeline
  - ReferenceGenomeDir
  - VariantCallingMode
