---
Version: 1.0
ApplicationName: DEnrichment_Somatic_IDT_Gms560
BaseApplication: DragenEnrichment
BaseVersion: 1.0
BaseApplicationPath: ../../base/dragen/DragenEnrichment.yaml

Data:
  GermlineOrSomatic: somatic
