---
# config file for SampleSheetCreator

Methods:
    Archer_VariantPlex_DNA_RNA:
        SampleSheetRoot:
        Instrument: ['nextseq','miseq']
        Indices: 'G:\Genetik\Mjukvaror\SampleSheetConfigs\config\indices_181217.yaml'
        Header:
            IEMFileVersion: 4
            Workflow: "GenerateFASTQ"
            Application: "FASTQ Only"
            Assay: "Nextera"
            Chemistry: "Amplicon"
        Settings:
            Adapter: "CTGTCTCTTATACACATCT"
        Reads: [151,151]
        Panels:
            Solid_tumor:
                AnalysisDefPathWin: 'G:\Genetik\Mjukvaror\SampleSheetConfigs\analysis_defs\Archer_VariantPlex_DNA_RNA\Solid_tumor'
                AnalysisDefPathUX: '/home/genetik/calls2xls/designfiles'
                PanelTargetPathUX: '/home/genetik/calls2xls/diseasegenelists'                
                Manifests:
                    A: "-"
                PanelTarget: 'NA'
            Myeloid:
                AnalysisDefPathWin: 'G:\Genetik\Mjukvaror\SampleSheetConfigs\analysis_defs\Archer_VariantPlex_DNA_RNA\Myeloid'
                AnalysisDefPathUX: '/home/genetik/calls2xls/designfiles'
                PanelTargetPathUX: '/home/genetik/calls2xls/diseasegenelists'
                Manifests:
                    A: "-"
                PanelTarget: 'NA'
            Fusion:
                AnalysisDefPathWin: 'G:\Genetik\Mjukvaror\SampleSheetConfigs\analysis_defs\Archer_VariantPlex_DNA_RNA\Fusion'
                AnalysisDefPathUX: '/home/genetik/calls2xls/designfiles'
                PanelTargetPathUX: '/home/genetik/calls2xls/diseasegenelists'
                Manifests:
                    A: "-"
                PanelTarget: 'NA'
            Solid_tumor_BRCA:
                AnalysisDefPathWin: 'G:\Genetik\Mjukvaror\SampleSheetConfigs\analysis_defs\Archer_VariantPlex_DNA_RNA\Solid_tumor_BRCA'
                AnalysisDefPathUX: '/home/genetik/calls2xls/designfiles'
                PanelTargetPathUX: '/home/genetik/calls2xls/diseasegenelists'
                Manifests:
                    A: "-"
                PanelTarget: 'NA'
    Agilent_Haloplex_DNA:
        SampleSheetRoot:
        Instrument: ['miseq']
        Indices: 'G:\Genetik\Mjukvaror\SampleSheetConfigs\config\indices_181217.yaml'        
        Header:
            IEMFileVersion: 4
            Workflow: "Custom Amplicon"
            Application: "FASTQ Only"
            Assay: "TruSeq LT"
            Chemistry: "Default"
        Settings:
            ReverseComplement: 0
        Reads: [151,151]
        Panels:
            Cardio:
                AnalysisDefPathWin: 'G:\Genetik\Mjukvaror\SampleSheetConfigs\analysis_defs\Agilent_Haloplex_DNA\Cardio'
                AnalysisDefPathUX: '/home/genetik/calls2xls/designfiles'
                PanelTargetPathUX: '/home/genetik/calls2xls/diseasegenelists'
                Manifests: 
                    A: '-'
                PanelTarget: 'LKPN_design_III_17150-1413761621.bed'
