---
# run.yaml

RunDataDefaults:
  Investigator: "NA"
  Instrument: "NA"
  Flowcell: "NA"
  SampleSheetVersion: "NA"
  RunName: "NA"
  RunDescription: "NA"
  ReadCycles: "NA"
  ReagentKit: "NA"
  I5SampleSheetOrientation: "NA"
  I5SeqOrientation: "NA"
  Lanes: "NA"
  Chemistry: "NA"
  FastqExtractTool: "NA"
  AssessBalance: "NA"
  A: "NA"
  T: "NA"
  G: "NA"
  C: "NA"

RunViewWidgets:
  General:
    Investigator: label
    Instrument: label
    Flowcell: label
    SampleSheetVersion: label
    RunName: label
    RunDescription: label
  Sequencing:
    I5SampleSheetOrientation: label
    Lanes: label
    ReagentKit: label
    ReadCycles: label
    Chemistry: label
    FastqExtractTool: label
  Validation:
    I5SeqOrientation: label
    AssessBalance: label
  Fluorophores:
    A: label
    T: label
    G: label
    C: label

RunSetupWidgets:
  General:
    Investigator: combobox
    RunName: lineedit
    RunDescription: lineedit
    Instrument: combobox
    Flowcell: combobox
  SampleSheet and Validation:
    ReagentKit: combobox
    ReadCycles: combobox
    CustomReadCycles: lineedit
    SampleSheetVersion: lineedit

ReadCycles:
  151-8-8-151:
    Read1Cycles: 151
    Read2Cycles: 151
    Index1Cycles: 8
    Index2Cycles: 8
  151-10-10-151:
    Read1Cycles: 151
    Read2Cycles: 151
    Index1Cycles: 10
    Index2Cycles: 10

FastqExtractTool:
  - bcl2fastq
  - bclconvert
