---
# run.yaml

Defaults:
    Instrument: "NA"
    SampleSheetVersion: "NA"
    RunName: "NA"
    RunDescription: "NA"
    ReadCycles: "NA"
    I5IndexOrientation: "NA"
    Lanes: "NA"
    Investigator: "NA"


SetupUI:
  Header:
    Instrument: combobox
    SampleSheetVersion: lineedit
    RunName: lineedit
    RunDescription: lineedit

  Reads:
    ReadCycles: combobox
    I5IndexOrientation: lineedit

  Extra:
    Lanes: combobox
    Investigator: lineedit

DataHierarchy:
  NovaSeqX:
    SampleSheetVersion: "2"
    Lanes: ["2", "8"]
    ReadCycles: ["151-8-8-151", "151-10-10-151"]
    I5IndexOrientation: "fwd"
  NextSeq500:
    SampleSheetVersion: "1"
    Lanes: ["1"]
    ReadCycles: [ "NA" ]
    I5IndexOrientation: "rc"
  MiSeq:
    SampleSheetVersion: "1"
    Lanes: [ "1" ]
    ReadCycles: [ "NA" ]
    I5IndexOrientation: "fwd"


ReadCycles:
  151-8-8-151:
    Read1Cycles: 151
    Read2Cycles: 151
    Index1Cycles: 8
    Index2Cycles: 8
  151-10-10-151:
    Read1Cycles: 151
    Read2Cycles: 151
    Index1Cycles: 10
    Index2Cycles: 10

