---
# run.yaml

RunDataFields:
  - Date
  - Investigator
  - Instrument
  - Flowcell
  - SampleSheetVersion
  - RunName
  - RunDescription
  - ReadCycles
  - ReagentKit
  - I5SampleSheetOrientation
  - I5SeqOrientation
  - Lanes
  - Chemistry
  - FastqExtractTool
  - AssessBalance
  - UUID7

ReadCyclesFields:
  - Read1Cycles
  - Read2Cycles
  - Index1Cycles
  - Index2Cycles

RunDataDefaults:
  Date: "NA"
  Investigator: "NA"
  Instrument: "NA"
  Flowcell: "NA"
  SampleSheetVersion: "NA"
  RunName: "NA"
  RunDescription: "NA"
  ReadCycles: "NA"
  ReagentKit: "NA"
  I5SampleSheetOrientation: "NA"
  I5SeqOrientation: "NA"
  Lanes: "NA"
  Chemistry: "NA"
  FastqExtractTool: "NA"
  AssessBalance: "NA"
  UUID7: "NA"
  A: "NA"
  T: "NA"
  G: "NA"
  C: "NA"

RunViewWidgets:
  General:
    Investigator: label
    Instrument: label
    Flowcell: label
    SampleSheetVersion: label
    RunName: label
    RunDescription: label
  Sequencing:
    I5SampleSheetOrientation: label
    Lanes: label
    ReagentKit: label
    ReadCycles: label
    Chemistry: label
    FastqExtractTool: label
  Validation:
    I5SeqOrientation: label
    AssessBalance: label
  Fluorophores:
    A: label
    T: label
    G: label
    C: label

RunSetupWidgets:
  General:
    Investigator: combobox
    RunName: lineedit
    RunDescription: lineedit
    Instrument: combobox
    Flowcell: combobox
  SampleSheet and Validation:
    FastqExtractTool: combobox
    ReagentKit: combobox
    ReadCycles: combobox
    CustomReadCycles: lineedit

FastqExtractTool:
  - bcl2fastq
  - bclconvert
