---
# run.yaml

RunDataFields:
  - Date
  - Investigator
  - Instrument
  - Flowcell
  - SampleSheetVersion
  - RunName
  - RunDescription
  - ReadCycles
  - CustomReadCycles
  - ReagentKit
  - I5SampleSheetOrientation
  - I5SeqOrientation
  - Lanes
  - Chemistry
  - FastqExtractTool
  - AssessBalance
  - UUID7

ReadCyclesFields:
  - Read1Cycles
  - Index1Cycles
  - Index2Cycles
  - Read2Cycles

RunDataDefaults:
  Date: "NA"
  Investigator: "NA"
  Instrument: "NA"
  Flowcell: "NA"
  SampleSheetVersion: "NA"
  RunName: "NA"
  RunDescription: "NA"
  ReadCycles: "NA"
  ReagentKit: "NA"
  I5SampleSheetOrientation: "NA"
  I5SeqOrientation: "NA"
  Lanes: "NA"
  Chemistry: "NA"
  FastqExtractTool: "NA"
  AssessBalance: "NA"
  UUID7: "NA"
  A: "NA"
  T: "NA"
  G: "NA"
  C: "NA"

RunViewFields:
  General:
    - Date
    - Investigator
    - RunName
    - RunDescription
  Sequencing:
    - Instrument
    - Flowcell
    - Lanes
    - ReagentKit
    - Chemistry
    - I5SeqOrientation
  ReadCycles:
    - Read1Cycles
    - Index1Cycles
    - Index2Cycles
    - Read2Cycles
  I5SampleSheetOrientation:
    - BCL2Fastq
    - BCLConvert
  Validation:
    - AssessColorBalance
  Colors:
    - A
    - T
    - G
    - C

RunSetupWidgets:
  General:
    Investigator: combobox
    RunName: lineedit
    RunDescription: lineedit
    Instrument: combobox
    Flowcell: combobox
  SampleSheet and Validation:
    FastqExtractTool: combobox
    ReagentKit: combobox
    ReadCycles: combobox
    CustomReadCycles: lineedit

FastqExtractTool:
  - bcl2fastq
  - bclconvert
