---
# run.yaml

RunDataDefaults:
  Investigator: "NA"
  Instrument: "NA"
  Flowcell: "NA"
  SampleSheetVersion: "NA"
  RunName: "NA"
  RunDescription: "NA"
  ReadCycles: "NA"
  I5SampleSheetOrientation: "NA"
  I5SeqOrientation: "NA"
  Lanes: "NA"
  Chemistry: "NA"
  FastqExtractTool: "NA"
  AssessBalance: "NA"
  A: "NA"
  T: "NA"
  G: "NA"
  C: "NA"

RunViewWidgets:
  General:
    Investigator: lineedit
    Instrument: lineedit
    Flowcell: lineedit
    SampleSheetVersion: lineedit
    RunName: lineedit
    RunDescription: lineedit
  Sequencing:
    ReadCycles: lineedit
    I5SampleSheetOrientation: lineedit
    I5SeqOrientation: lineedit
    Lanes: lineedit
    Chemistry: lineedit
    FastqExtractTool: lineedit
  Validation:
    AssessBalance: lineedit
  Fluorophores:
    A: lineedit
    T: lineedit
    G: lineedit
    C: lineedit

RunSetupWidgets:
  General:
    Investigator: combobox
    RunName: lineedit
    RunDescription: lineedit
    Instrument: combobox
    Flowcell: combobox
    SampleSheetVersion: lineedit
  SampleSheet and Validation:
    ReadCycles: combobox
    CustomReadCycles: lineedit

ReadCycles:
  151-8-8-151:
    Read1Cycles: 151
    Read2Cycles: 151
    Index1Cycles: 8
    Index2Cycles: 8
  151-10-10-151:
    Read1Cycles: 151
    Read2Cycles: 151
    Index1Cycles: 10
    Index2Cycles: 10

FastqExtractTool:
  - bcl2fastq
  - bclconvert
