# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\preferences_dlg.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(634, 452)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_institute = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_institute.setObjectName("lineEdit_institute")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_institute)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_configfile = QtWidgets.QHBoxLayout()
        self.horizontalLayout_configfile.setObjectName("horizontalLayout_configfile")
        self.lineEdit_config_file = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_config_file.setObjectName("lineEdit_config_file")
        self.horizontalLayout_configfile.addWidget(self.lineEdit_config_file)
        self.toolButton_config_file = QtWidgets.QToolButton(Dialog)
        self.toolButton_config_file.setObjectName("toolButton_config_file")
        self.horizontalLayout_configfile.addWidget(self.toolButton_config_file)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_configfile)
        self.lbl_1 = QtWidgets.QLabel(Dialog)
        self.lbl_1.setObjectName("lbl_1")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_indices_file = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_indices_file.setObjectName("lineEdit_indices_file")
        self.horizontalLayout.addWidget(self.lineEdit_indices_file)
        self.toolButton_indices_file = QtWidgets.QToolButton(Dialog)
        self.toolButton_indices_file.setObjectName("toolButton_indices_file")
        self.horizontalLayout.addWidget(self.toolButton_indices_file)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_samplesheets_folder = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_samplesheets_folder.setObjectName("lineEdit_samplesheets_folder")
        self.horizontalLayout_4.addWidget(self.lineEdit_samplesheets_folder)
        self.toolButton_samplesheets_folder = QtWidgets.QToolButton(Dialog)
        self.toolButton_samplesheets_folder.setObjectName("toolButton_samplesheets_folder")
        self.horizontalLayout_4.addWidget(self.toolButton_samplesheets_folder)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_add_investigator = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_add_investigator.setObjectName("lineEdit_add_investigator")
        self.horizontalLayout_5.addWidget(self.lineEdit_add_investigator)
        self.pushButton_add_investigator = QtWidgets.QPushButton(Dialog)
        self.pushButton_add_investigator.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_add_investigator.setObjectName("pushButton_add_investigator")
        self.horizontalLayout_5.addWidget(self.pushButton_add_investigator)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.pushButton_remove_investigators = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_remove_investigators.sizePolicy().hasHeightForWidth())
        self.pushButton_remove_investigators.setSizePolicy(sizePolicy)
        self.pushButton_remove_investigators.setMinimumSize(QtCore.QSize(120, 0))
        self.pushButton_remove_investigators.setObjectName("pushButton_remove_investigators")
        self.horizontalLayout_5.addWidget(self.pushButton_remove_investigators)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.listWidget_investigators = QtWidgets.QListWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listWidget_investigators.sizePolicy().hasHeightForWidth())
        self.listWidget_investigators.setSizePolicy(sizePolicy)
        self.listWidget_investigators.setMinimumSize(QtCore.QSize(100, 100))
        self.listWidget_investigators.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget_investigators.setMovement(QtWidgets.QListView.Static)
        self.listWidget_investigators.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget_investigators.setObjectName("listWidget_investigators")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.listWidget_investigators)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_analysis_file = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_analysis_file.setObjectName("lineEdit_analysis_file")
        self.horizontalLayout_3.addWidget(self.lineEdit_analysis_file)
        self.toolButton_analysis_file = QtWidgets.QToolButton(Dialog)
        self.toolButton_analysis_file.setObjectName("toolButton_analysis_file")
        self.horizontalLayout_3.addWidget(self.toolButton_analysis_file)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Institute"))
        self.label_6.setText(_translate("Dialog", "Config yaml"))
        self.toolButton_config_file.setText(_translate("Dialog", "..."))
        self.lbl_1.setText(_translate("Dialog", "Indices yaml"))
        self.toolButton_indices_file.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "SampleSheets folder"))
        self.toolButton_samplesheets_folder.setText(_translate("Dialog", "..."))
        self.pushButton_add_investigator.setText(_translate("Dialog", "Add"))
        self.pushButton_remove_investigators.setText(_translate("Dialog", "Remove selected"))
        self.label_5.setText(_translate("Dialog", "Investigator"))
        self.label.setText(_translate("Dialog", "Analysis yaml"))
        self.toolButton_analysis_file.setText(_translate("Dialog", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
