---
# run_settings.yaml

Header:
  FileFormatVersion:
    control: label
    data: "2"
  RunName:
    control: lineedit
    data: 'Unknown'
  RunDescription:
    control: lineedit
    data: 'Unknown'
  Instrument:
    control: combobox
    data: ['NovaSeqX']

Reads:
  ReadProfile:
    control: combobox
    data: ['151-10-10-151']

#Sequencing_Settings:
#  InputContainerIdentifier:
#    control: lineedit
#    data: 'Unknown'

Run_Extra:
  FlowCellType:
    control: combobox
    data: ['1,5B', '10B', '25B']
  Investigator:
    control: lineedit
    data: "Unknown"

#    LibraryPrepKits:
#      control: label
#      data: ''

#Data_Translate:
#  ReadProfile:
#    '151-10-10-151':
#      Read1Cycles: 151
#      Read2Cycles: 151
#      Index1Cycles: 10
#      Index2Cycles: 10
#  Instrument:
#    'NovaSeqX':
#      InstrumentPlatform: 'NovaSeqXSeries'
#      InstrumentType: 'NovaSeqX'


#Custom_Lab_Data:
#  Investigator:
#    data: []
#    control: lineedit
#  WorkList:
#    data: []
#    control: label
